---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```
#tableMatrix

`tableMatrix` package provides structure to store data. It is mainly useful for datasets which have following condition: some columns describe data and main data could be stored as matrix. `tableMatrix` purpose is to get faster access.

##Installation
From github:
```{r eval=FALSE}
# install.packages("devtools")
devtools::install_github("InferenceTechnologies/tableMatrix")
```

##Examples

Creation of `tableMatrix` with 2 datasets.

```{r  fig.path='figures/README-'}
data(images8By8)
colnames(images8By8)
dim(images8By8)
data(images15By15)
dim(images15By15)

tm <- tableMatrix(list(images15By15, images8By8),
list(1:3, 1:3), list(c(4:ncol(images15By15)),c(4:ncol(images8By8))), list(c(15,15), c(8,8)))

tm$tab

tm$matDim

#get data from second matrix where direction is "both"
tabSub <- tm[.(2)][direction=="both"]

imageMean <- colMeans(mat(tabSub,1))
dim(imageMean) <- getRowDim(tabSub,1)

image(imageMean)

```
